name: Line_Lite
description: Line Chat Application - UEE Project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:
  dio:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_app_name: ^0.1.1
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "Line Lite"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_name:
  name: "Line Lite"
# The following section is specific to Flutter.
flutter:
  assets:
     - assets/images/
     - assets/images/Backstreet Girls.jpg
     - assets/images/Family Club.jpg
     - assets/images/Funny Folk.jpg
     - assets/images/Girls on Fire.jpg
     - assets/images/Gossip News.jpg
     - assets/images/man 1.jpg
     - assets/images/man 2.jpg
     - assets/images/man 3.jpg
     - assets/images/man 4.jpg
     - assets/images/Market Yard.jpg
     - assets/images/My Family.png
     - assets/images/Pen Pals.jpg
     - assets/images/woman 1.jpg
     - assets/images/woman 2.jpg
     - assets/images/woman 3.jpg
     - assets/images/woman 4.jpg
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#   assets:
#      - images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
#     - images/Backstreet Girls.jpg
#     - images/Family Club.jpg
#     - images/Funny Folk.jpg
#     - images/Girls on Fire.jpg
#     - images/Gossip News.jpg
#     - images/man 1.jpg
#     - images/man 2.jpg
#     - images/man 3.jpg
#     - images/Market Yard.jpg
#     - images/My Family.jpg
#     - images/Pen Pals.jpg
#     - images/woman 1.jpg
#     - images/woman 2.jpg
#     - images/woman 3.jpg
#     - images/woman 4.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
